-- begin FORESTGUMP_ORDER
alter table FORESTGUMP_ORDER add constraint FK_FORESTGUMP_ORDER_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_FORESTGUMP_ORDER_ON_USER on FORESTGUMP_ORDER (USER_ID)^
-- end FORESTGUMP_ORDER
-- begin FORESTGUMP_ORDER_ITEM
alter table FORESTGUMP_ORDER_ITEM add constraint FK_FORESTGUMP_ORDER_ITEM_ON_ORDER foreign key (ORDER_ID) references FORESTGUMP_ORDER(ID)^
alter table FORESTGUMP_ORDER_ITEM add constraint FK_FORESTGUMP_ORDER_ITEM_ON_MENU_ITEM foreign key (MENU_ITEM_ID) references FORESTGUMP_MENU_ITEM(ID)^
create index IDX_FORESTGUMP_ORDER_ITEM_ON_ORDER on FORESTGUMP_ORDER_ITEM (ORDER_ID)^
create index IDX_FORESTGUMP_ORDER_ITEM_ON_MENU_ITEM on FORESTGUMP_ORDER_ITEM (MENU_ITEM_ID)^
-- end FORESTGUMP_ORDER_ITEM
